### PR TITLE
Detect 404s from Stanford's PURL service

### LINKED ISSUE #621: [HyBox/production] ActiveFedora::RecordInvalid: Validation failed: Title You must provide a title
## Backtrace

    line 69 of [PROJECT_ROOT]/app/jobs/import_work_from_purl_job.rb: process_collection
    line 40 of [PROJECT_ROOT]/app/jobs/import_work_from_purl_job.rb: process_attributes
    line 26 of [PROJECT_ROOT]/app/jobs/import_work_from_purl_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/32354220)

### LINKED ISSUE #752: [HyBox/production] ActiveFedora::RecordInvalid: Validation failed: Title You must provide a title
## Backtrace

    line 71 of [PROJECT_ROOT]/app/jobs/import_work_from_purl_job.rb: process_collection
    line 40 of [PROJECT_ROOT]/app/jobs/import_work_from_purl_job.rb: process_attributes
    line 26 of [PROJECT_ROOT]/app/jobs/import_work_from_purl_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/32634980)

### PR DESCRIPTION
**Pull request by jcoyne**
Raise an error when this happens.

Fixes #621
Fixes #752

### CODE REVIEW

**Comment by jcoyne** [comment]
@cbeer previously it went on to parse the 404 message as DC xml, so yes, we're catching this error (but not in the Ruby language sense).

**Comment by mjgiarlo** [comment]
@jcoyne thoughts on @cbeer's Faraday suggestion?

**Comment by cbeer** [comment]
> we're catching this error (but not in the Ruby language sense)

Right. I'm suggesting the commit message might be clarified. "Handle", perhaps?

**Comment by jcoyne** [comment]
@cbeer better?

**Comment by cbeer** [comment]
Thanks, much less confusing. I still wonder if it'd be better to enable Faraday's exceptions?

**Comment by jcoyne** [comment]
@cbeer I'm not seeing anything about that on the Faraday README or wiki. Can you point me to something showing what you are referring to?

**Comment by cbeer** [comment]
e.g: http://mislav.net/2011/07/faraday-advanced-http/

**Comment by jcoyne** [comment]
@cbeer Thanks. I've updated accordingly.

**Comment by jcoyne** [comment]
@cbeer unfortunately that didn't work.  That blog post seems to be very out of date. I don't see any updated instructions for doing what is suggested there.

**Comment by cbeer** [comment]
Ok. We've done this very thing in bunch of other projects: https://github.com/search?l=Ruby&q=org%3Asul-dlss+raiseerror&type=Code

**Comment by jcoyne** [comment]
@cbeer I did exactly that, but my test comes back with nil in the body.  Do those other examples have tests?

**Comment by jcoyne** [comment]
@cbeer 
```ruby
(byebug) p conn
#<Faraday::Connection:0x007fbf65afbf28 @parallel_manager=nil, @headers={"User-Agent"=>"Faraday v0.9.2"}, @params={}, @options=#<Faraday::RequestOptions (empty)>, @ssl=#<Faraday::SSLOptions (empty)>, @default_parallel_manager=nil, @builder=#<Faraday::RackBuilder:0x007fbf65afbbe0 @handlers=[Faraday::Response::RaiseError], @app=#<Faraday::Response::RaiseError:0x007fbf65ab7e90 @app=#<Proc:0x007fbf65ab7fa8@/Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:152 (lambda)>>>, @url_prefix=#<URI::HTTPS https://purl.stanford.edu/>, @proxy=nil>
#<Faraday::Connection:0x007fbf65afbf28 @parallel_manager=nil, @headers={"User-Agent"=>"Faraday v0.9.2"}, @params={}, @options=#<Faraday::RequestOptions (empty)>, @ssl=#<Faraday::SSLOptions (empty)>, @default_parallel_manager=nil, @builder=#<Faraday::RackBuilder:0x007fbf65afbbe0 @handlers=[Faraday::Response::RaiseError], @app=#<Faraday::Response::RaiseError:0x007fbf65ab7e90 @app=#<Proc:0x007fbf65ab7fa8@/Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:152 (lambda)>>>, @url_prefix=#<URI::HTTPS https://purl.stanford.edu/>, @proxy=nil>
(byebug) req = conn.get(path)
#<Faraday::Response:0x007fbf6213bd10 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:get @url=#<URI::HTTPS https://purl.stanford.edu/bc390xk2647.xml> @request=#<Faraday::RequestOptions (empty)> @request_headers={"User-Agent"=>"Faraday v0.9.2"} @ssl=#<Faraday::SSLOptions (empty)> @response=#<Faraday::Response:0x007fbf6213bd10 ...>>>
(byebug) req.status
nil
(byebug) req.body
nil
```

**Comment by jcoyne** [comment]
The catch is you also have to add `faraday.adapter :httpclient`

**Pull request merged**
