### PR TITLE
Mutlitenancy in test

### PR DESCRIPTION
**Pull request by atz**
See #989 where this was all debated over being merged into a branch that was thrown away.  But we actually want this.

### CODE REVIEW

**Comment by atz** [comment]
Our new strictness makes fake tenant accounts inadequate.  Trying to fix.

**Comment by atz** [comment]
All fixed... except for one failure in "push".

**Comment by mjgiarlo** [comment]
Here's the one failure:
```
  1) SolrEndpoint#connection returns the initialized connection (without an adapter option)
     Failure/Error: af_defaults = ActiveFedora::SolrService.instance.conn.options
     
       RSolr received :connect with unexpected arguments
         expected: ({"read_timeout"=>120, "open_timeout"=>120, "url"=>"http://example.com/solr/"})
              got: ({:read_timeout=>120, :open_timeout=>120, :url=>"http://127.0.0.1:8985/solr/hydra-test"})
       Diff:
       @@ -1,2 +1,4 @@
       -[{"read_timeout"=>120, "open_timeout"=>120, "url"=>"http://example.com/solr/"}]
       +[{:read_timeout=>120,
       +  :open_timeout=>120,
       +  :url=>"http://127.0.0.1:8985/solr/hydra-test"}]
       
        Please stub a default value first if message might be received with other args as well. 
     # ./app/models/solr_endpoint.rb:14:in `connection_options'
     # ./app/models/solr_endpoint.rb:8:in `connection'
     # ./spec/models/solr_endpoint_spec.rb:12:in `block (3 levels) in <top (required)>'
     # ./spec/models/solr_endpoint_spec.rb:24:in `block (3 levels) in <top (required)>'
```

@atz @jcoyne @cbeer I have seen this one before, but it it usually resolved by restarting the build. That said, do y'all think this is something we should be worrying about? I ask because we have Solr connection issues in demo-land -- maybe they're not connected, though.

**Comment by atz** [comment]
Why can't I get this locally though?

**Pull request merged**
