### PR TITLE
Removes duplicate chevron from facets.

### LINKED ISSUE #532: Duplicate chevron in facet toggle
double-chevron

### PR DESCRIPTION
**Pull request by andjsmit**
Fixes #532 

Also requires same change in Hyrax ( https://github.com/projecthydra-labs/hyrax/pull/39 ) to be in place.

### CODE REVIEW

**Comment by jcoyne** [comment]
If this is going to be in Hyrax, do we need to duplicate this style in Hyku?

**Comment by jcoyne** [comment]
As these styles were added in an attempt to fix the admin page, have you confirmed the admin page still works correctly?
 https://github.com/projecthydra-labs/hyku/commit/ff3417bad6ba67f4f00f8cf79a650aeb4af2ad09

**Comment by andjsmit** [comment]
1. The styles are duplicated from hyrax, so we could remove the styles from hyku and trust that hyrax will take care of it.

2. The style is still applies to admin page as the menus there are list based instead of div. The change just prevents the styles from being used in the div based facet menus.

**Comment by jcoyne** [comment]
> The styles are duplicated from hyrax, so we could remove the styles from hyku and trust that hyrax will take care of it.

👍

**Comment by mjgiarlo** [comment]
@andjsmit Does that mean should close this PR and go with the one in Hyrax?

Thanks for taking this on.

**Comment by andjsmit** [comment]
@mjgiarlo How about I update this pull request to remove the duplicated styles and to add a needed class to the admin sidebar? Without, this issue will still occur. That was my plan at this point. Thanks.

**Comment by mjgiarlo** [comment]
@andjsmit :ok_hand:

**Comment by andjsmit** [comment]
@jcoyne @mjgiarlo Ready for review. It anticipates the change already made in hyrax by removing some duplicated styles and adds an identifying class to the admin sidebar. Thanks.

**Comment by mjgiarlo** [comment]
@andjsmit how would you feel about running `bundle update hyrax` and including the changes to `Gemfile.lock` in this PR?

**Comment by andjsmit** [comment]
@mjgiarlo Ran `bundle update hyrax` as requested. Getting conflict now though and build broke though I don't think the Gemfile.lock is to blame.

**Comment by mjgiarlo** [comment]
@andjsmit Dang. Taking a look at the conflict.

**Comment by mjgiarlo** [comment]
@andjsmit Merge conflict resolved.

**Comment by mjgiarlo** [comment]
New merge conflict resolved.

**Pull request merged**
