### PR TITLE
Adds config for log capture via logz.io

### PR DESCRIPTION
**Pull request by bbranan**
Installs Filebeat (https://www.elastic.co/products/beats/filebeat) via Elastic Beanstalk extentions for shipping logs to logz.io.

### CODE REVIEW

**Comment by atz** [comment]
I have no way to evaluate this technically, but looks OK to me.

**Comment by bbranan** [comment]
Upon further testing, it looks like I will need to make a few tweaks to allow all defined logs to be shipped properly. Let's hold off on merging this one until I'm able to make those changes.

**Comment by bbranan** [comment]
@eefahy this is ready to merge

**Comment by jcoyne** [comment]
Should we install https://github.com/dwbutler/logstash-logger ?

**Comment by bbranan** [comment]
@jcoyne We could, though we'd still need filebeat to capture the other logs (nginx, beanstalk, aws, etc), so we'd end up with log capture config in two places rather than one.

**Pull request merged**
