### PR TITLE
Temporarily turn off the rescuing of not found exceptions

### PR DESCRIPTION
**Pull request by jcoyne**
So that we can figure out why non-admins can't submit works.
Ref https://github.com/projecthydra-labs/hyrax/issues/753

### CODE REVIEW

**Comment by atz** [comment]
Apparently we weren't testing for this behavior anywhere?

**Comment by jcoyne** [comment]
This behavior is built int every rails application, so it's tested in rails itself

**Comment by atz** [comment]
Why isn't it enough to do this locally?

**Comment by jcoyne** [comment]
I'm only able to reproduce it on the demo server

**Comment by atz** [comment]
Crap, this means we're going to get tons of Honeybadger notifications, right?

**Pull request merged**
