### PR TITLE
Bump version to 1.0.0.beta

### PR DESCRIPTION
**Pull request by mjgiarlo**

### CODE REVIEW

**Comment by jcoyne** [comment]
Do you want to make this beta1 so we can better differentiate multiple beta releases?

**Comment by mjgiarlo** [comment]
@jcoyne Done.

**Comment by jcoyne** [comment]
@mjgiarlo do you mind if we fix the attachment bug first or do you want to ship it now?

**Comment by mjgiarlo** [comment]
@jcoyne Pls do fix the file attachment bug first. Thanks!

**Comment by jcoyne** [comment]
@mjgiarlo pushed and tagged the release.

**Pull request merged**
