### PR TITLE
Sidebar collapse

### LINKED ISSUE #895: Workflows menu collapses when I choose "Review Submissions"
It should stay expanded.

### PR DESCRIPTION
**Pull request by atz**
Fixes #895

### CODE REVIEW

**Comment by atz** [comment]
Well, it happened again.  I picked up the ticket and worked it to completion only to have one of the files deleted from underneath me and the targeted code relocated (complete with the same bugs).

**Comment by jcoyne** [comment]
@atz what file are you talking about?

**Comment by jeremyf** [comment]
Did it move to `app/views/hyrax/dashboard/_sidebar.html.erb`?

**Comment by jcoyne** [comment]
That happened 2 weeks ago so, I'm surprised that caught you: https://github.com/projecthydra-labs/hyku/commit/c29f9f73ccbf86e113d4cbfef26af71ac7b7ba6c#diff-645de999fa85cff385e107413a7e7617 I would have called it out otherwise. Sorry.

**Comment by atz** [comment]
Replacing this PR w/ a new one

**Pull request closed without merging**
